### PR TITLE
New Courses Taken Page

### PR DESCRIPTION
**Pull request by jessicalee2005**
listed some classes (tent)
uses searchbar/dropdown menu filter
select classes on the right (+ remove button)

### CODE REVIEW

**Comment by duc-beluga** [comment]
Hey Jessica,
What is the file ``public.code-workspace`` for?

**Comment by jessicalee2005** [comment]
sorry i'm not sure, but it appeared when I was merging it so I kept it just incase

**Comment by duc-beluga** [comment]
No worries! Seems like a file that holds your VSCode Workspace configurations. It's okay to delete it or you can just add it into ``.gitignore``

**Comment by duc-beluga** [comment]
Hey, I know it might be a bit of a change, but our project is using TailwindCSS and DaisyUI for styling. Would you mind using the built-in Tailwind classes for consistency?

**Comment by jessicalee2005** [comment]
ok! is it alright if I make those changes by monday sorry I never used tailwind before

**Comment by duc-beluga** [comment]
Sure :))

**Pull request closed without merging**
