### PR TITLE
Tailwind/daisy2

### PR DESCRIPTION
**Pull request by jessicalee2005**

### CODE REVIEW

**Comment by duc-beluga** [comment]
Hey Jessica, I'll edit your file and you can review my code too :))

**Comment by jessicalee2005** [comment]
thank you for helping me

**Comment by duc-beluga** [comment]
My pleasure :)) Always happy to help

**Review by duc-beluga — COMMENTED** [review]
Hey Jessica, 
I have cleaned up some up the code as well as being able to remove the CSS file. Please review it before I merge it into our main branch :))

**Comment by jessicalee2005** [comment]
looks good ! thank you for your help

**Review by duc-beluga — APPROVED** [review]
lgtm!

**Pull request merged**
