### PR TITLE
Client Error Page

### PR DESCRIPTION
**Pull request by cgensheimer**
very very basic

Screenshot 2024-03-04 at 17 55 57

### CODE REVIEW

**Comment by cgensheimer** [comment]
Merge conflicts are extremely simple and will be resolved upon approval

**Comment by duc-beluga** [comment]
I think you haven't pull the latest changes from main. I resolved the conflict. Try to ``git pull`` from both **main** and **error-page-404**. Then, ``git merge`` **error-page-404** with main and see if it works on your machine.

**Comment by cgensheimer** [comment]
> I think you haven't pull the latest changes from main. I resolved the conflict. Try to `git pull` from both **main** and **error-page-404**. Then, `git merge` **error-page-404** with **main** and see if it works on your machine.


Shouldn't be an issue, the auto merge with main will bring it up to date with all the commits since the conflicts are resolved. "Merging can be performed automatically with 1 approving review," but is blocked until you approve it.

**Comment by duc-beluga** [comment]
Oh yea, you're right. I thought there were more than 2 files changed and some in the main was overwritten.

**Review by duc-beluga — APPROVED** [review]
lgtm!

**Pull request merged**
